[theme]
# Primary accent color for interactive elements
primaryColor = "#009e73"

# Background color for the main content area
backgroundColor = "#0e1117"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#31333F"

# Color used for almost all text
textColor = "#fafafa"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
enableCORS = false
